kernel-5.14.0-238.el9
* Wed Jan 18 2023 Herton R. Krzesinski <herton@redhat.com> [5.14.0-238.el9]
- net/mlx5: Eswitch, Fix forwarding decision to uplink (Mohammad Kabat) [2112940]
- RDMA/mlx5: Use the proper number of ports (Mohammad Kabat) [2112940]
- net/mlx5: Fix driver use of uninitialized timeout (Mohammad Kabat) [2112940]
- net/mlx5e: Ring the TX doorbell on DMA errors (Mohammad Kabat) [2112940]
- net/mlx5e: Fix capability check for updating vnic env counters (Mohammad Kabat) [2112940]
- net/mlx5e: CT: Use own workqueue instead of mlx5e priv (Mohammad Kabat) [2112940]
- net/mlx5: Lag, correct get the port select mode str (Mohammad Kabat) [2112940]
- net/mlx5e: Fix enabling sriov while tc nic rules are offloaded (Mohammad Kabat) [2112940]
- net/mlx5e: kTLS, Fix build time constant test in RX (Mohammad Kabat) [2112940]
- net/mlx5e: kTLS, Fix build time constant test in TX (Mohammad Kabat) [2112940]
- net/mlx5: Lag, decouple FDB selection and shared FDB (Mohammad Kabat) [2112940]
- net/mlx5: TC, allow offload from uplink to other PF's VF (Mohammad Kabat) [2112940]
- net/mlx5e: Fix matchall police parameters validation (Mohammad Kabat) [2112940]
- mellanox: mlx5: avoid uninitialized variable warning with gcc-12 (Mohammad Kabat) [2112940]
- net/mlx5: E-Switch, pair only capable devices (Mohammad Kabat) [2112940]
- net/mlx5e: CT: Fix cleanup of CT before cleanup of TC ct rules (Mohammad Kabat) [2112940]
- Revert "net/mlx5e: Allow relaxed ordering over VFs" (Mohammad Kabat) [2112940]
- net/mlx5: Fix mlx5_get_next_dev() peer device matching (Mohammad Kabat) [2112940]
- net/mlx5e: Update netdev features after changing XDP state (Mohammad Kabat) [2112940]
- vdpa/mlx5: Add support for reading descriptor statistics (Mohammad Kabat) [2112940]
- RDMA/mlx5: Remove duplicate pointer assignment in mlx5_ib_alloc_implicit_mr() (Mohammad Kabat) [2112940]
- net/mlx5: fix multiple definitions of mlx5_lag_mpesw_init / mlx5_lag_mpesw_cleanup (Mohammad Kabat) [2112940]
- net/mlx5: Support multiport eswitch mode (Mohammad Kabat) [2112940]
- net/mlx5: Remove unused argument (Mohammad Kabat) [2112940]
- net/mlx5: Lag, refactor lag state machine (Mohammad Kabat) [2112940]
- net/mlx5e: Add XDP SQs to uplink representors steering tables (Mohammad Kabat) [2112940]
- net/mlx5e: Correct the calculation of max channels for rep (Mohammad Kabat) [2112940]
- net/mlx5e: CT: Add ct driver counters (Mohammad Kabat) [2112940]
- net/mlx5e: Allow relaxed ordering over VFs (Mohammad Kabat) [2112940]
- net/mlx5e: Support partial GSO for tunnels over vlans (Mohammad Kabat) [2112940]
- net/mlx5e: IPoIB, Improve ethtool rxnfc callback structure in IPoIB (Mohammad Kabat) [2112940]
- net/mlx5e: Allocate virtually contiguous memory for reps structures (Mohammad Kabat) [2112940]
- net/mlx5e: Allocate virtually contiguous memory for VLANs list (Mohammad Kabat) [2112940]
- net/mlx5: Allocate virtually contiguous memory in pci_irq.c (Mohammad Kabat) [2112940]
- net/mlx5: Allocate virtually contiguous memory in vport.c (Mohammad Kabat) [2112940]
- net/mlx5: Inline db alloc API function (Mohammad Kabat) [2112940]
- net/mlx5: Add last command failure syndrome to debugfs (Mohammad Kabat) [2112940]
- net/mlx5: sparse: error: context imbalance in 'mlx5_vf_get_core_dev' (Mohammad Kabat) [2112940]
- net/mlx5: Expose mlx5_sriov_blocking_notifier_register / unregister APIs (Mohammad Kabat) [2112940]
- net/mlx5: Lag, add debugfs to query hardware lag state (Mohammad Kabat) [2112940]
- net/mlx5: Lag, use buckets in hash mode (Mohammad Kabat) [2112940]
- net/mlx5: Lag, refactor dmesg print (Mohammad Kabat) [2112940]
- net/mlx5: Support devices with more than 2 ports (Mohammad Kabat) [2112940]
- net/mlx5: Lag, use actual number of lag ports (Mohammad Kabat) [2112940]
- net/mlx5: Lag, use hash when in roce lag on 4 ports (Mohammad Kabat) [2112940]
- net/mlx5: Lag, support single FDB only on 2 ports (Mohammad Kabat) [2112940]
- net/mlx5: Lag, store number of ports inside lag object (Mohammad Kabat) [2112940]
- net/mlx5: Lag, filter non compatible devices (Mohammad Kabat) [2112940]
- net/mlx5: Lag, use lag lock (Mohammad Kabat) [2112940]
- net/mlx5: Lag, move E-Switch prerequisite check into lag code (Mohammad Kabat) [2112940]
- net/mlx5: devcom only supports 2 ports (Mohammad Kabat) [2112940]
- net/mlx5: Lag, expose number of lag ports (Mohammad Kabat) [2112940]
- net/mlx5: Increase FW pre-init timeout for health recovery (Mohammad Kabat) [2112940]
- net/mlx5: Add exit route when waiting for FW (Mohammad Kabat) [2112940]
- net/mlx5: Don't perform lookup after already known sec_path (Mohammad Kabat) [2112940]
- net/mlx5: Cleanup XFRM attributes struct (Mohammad Kabat) [2112940]
- net/mlx5: Remove not-supported ICV length (Mohammad Kabat) [2112940]
- net/mlx5: Simplify IPsec capabilities logic (Mohammad Kabat) [2112940]
- net/mlx5: Don't advertise IPsec netdev support for non-IPsec device (Mohammad Kabat) [2112940]
- net/mlx5: Make sure that no dangling IPsec FS pointers exist (Mohammad Kabat) [2112940]
- net/mlx5: Clean IPsec FS add/delete rules (Mohammad Kabat) [2112940]
- net/mlx5: Simplify HW context interfaces by using SA entry (Mohammad Kabat) [2112940]
- net/mlx5: Remove indirections from esp functions (Mohammad Kabat) [2112940]
- net/mlx5: Merge various control path IPsec headers into one file (Mohammad Kabat) [2112940]
- net/mlx5: Remove useless validity check (Mohammad Kabat) [2112940]
- net/mlx5: Store IPsec ESN update work in XFRM state (Mohammad Kabat) [2112940]
- net/mlx5: Reduce useless indirection in IPsec FS add/delete flows (Mohammad Kabat) [2112940]
- net/mlx5: Don't hide fallback to software IPsec in FS code (Mohammad Kabat) [2112940]
- net/mlx5: Check IPsec TX flow steering namespace in advance (Mohammad Kabat) [2112940]
- net/mlx5: Simplify IPsec flow steering init/cleanup functions (Mohammad Kabat) [2112940]
- net/mlx5: fs, an FTE should have no dests when deleted (Mohammad Kabat) [2112940]
- net/mlx5: fs, call the deletion function of the node (Mohammad Kabat) [2112940]
- net/mlx5: fs, delete the FTE when there are no rules attached to it (Mohammad Kabat) [2112940]
- net/mlx5: fs, do proper bookkeeping for forward destinations (Mohammad Kabat) [2112940]
- net/mlx5: fs, add unused destination type (Mohammad Kabat) [2112940]
- net/mlx5: fs, jump to exit point and don't fall through (Mohammad Kabat) [2112940]
- net/mlx5: fs, refactor software deletion rule (Mohammad Kabat) [2112940]
- net/mlx5: fs, split software and IFC flow destination definitions (Mohammad Kabat) [2112940]
- net/mlx5e: TC, set proper dest type (Mohammad Kabat) [2112940]
- net/mlx5e: Remove unused mlx5e_dcbnl_build_rep_netdev function (Mohammad Kabat) [2112940]
- net/mlx5e: Drop error CQE handling from the XSK RX handler (Mohammad Kabat) [2112940]
- net/mlx5: Print initializing field in case of timeout (Mohammad Kabat) [2112940]
- net/mlx5: Delete redundant default assignment of runtime devlink params (Mohammad Kabat) [2112940]
- net/mlx5: Remove useless kfree (Mohammad Kabat) [2112940]
- net/mlx5: use kvfree() for kvzalloc() in mlx5_ct_fs_smfs_matcher_create (Mohammad Kabat) [2112940]
- RDMA/mlx5: Clean UMR QP type flow from mlx5_ib_post_send() (Mohammad Kabat) [2112940]
- RDMA/mlx5: Use mlx5_umr_post_send_wait() to update xlt (Mohammad Kabat) [2112940]
- RDMA/mlx5: Use mlx5_umr_post_send_wait() to update MR pas (Mohammad Kabat) [2112940]
- RDMA/mlx5: Move creation and free of translation tables to umr.c (Mohammad Kabat) [2112940]
- RDMA/mlx5: Use mlx5_umr_post_send_wait() to rereg pd access (Mohammad Kabat) [2112940]
- RDMA/mlx5: Use mlx5_umr_post_send_wait() to revoke MRs (Mohammad Kabat) [2112940]
- RDMA/mlx5: Introduce mlx5_umr_post_send_wait() (Mohammad Kabat) [2112940]
- RDMA/mlx5: Expose wqe posting helpers outside of wr.c (Mohammad Kabat) [2112940]
- RDMA/mlx5: Simplify get_umr_update_access_mask() (Mohammad Kabat) [2112940]
- RDMA/mlx5: Move mkey ctrl segment logic to umr.c (Mohammad Kabat) [2112940]
- RDMA/mlx5: Move umr checks to umr.h (Mohammad Kabat) [2112940]
- RDMA/mlx5: Move init and cleanup of UMR to umr.c (Mohammad Kabat) [2112940]
- RDMA/mlx5: Fix flow steering egress flow (Mohammad Kabat) [2112940]
- mlx5, xsk: Diversify return values from xsk_wakeup call paths (Mohammad Kabat) [2112940]
- net/mlx5: Remove not-implemented IPsec capabilities (Mohammad Kabat) [2112940]
- net/mlx5: Remove ipsec_ops function table (Mohammad Kabat) [2112940]
- net/mlx5: Reduce kconfig complexity while building crypto support (Mohammad Kabat) [2112940]
- net/mlx5: Move IPsec file to relevant directory (Mohammad Kabat) [2112940]
- net/mlx5: Remove not-needed IPsec config (Mohammad Kabat) [2112940]
- net/mlx5: Align flow steering allocation namespace to common style (Mohammad Kabat) [2112940]
- net/mlx5: Unify device IPsec capabilities check (Mohammad Kabat) [2112940]
- net/mlx5: Remove useless IPsec device checks (Mohammad Kabat) [2112940]
- net/mlx5: Remove ipsec vs. ipsec offload file separation (Mohammad Kabat) [2112940]
- RDMA/mlx5: Drop crypto flow steering API (Mohammad Kabat) [2112940]
- RDMA/mlx5: Delete never supported IPsec flow action (Mohammad Kabat) [2112940]
- net/mlx5: Remove FPGA ipsec specific statistics (Mohammad Kabat) [2112940]
- net/mlx5: Remove XFRM no_trailer flag (Mohammad Kabat) [2112940]
- net/mlx5: Remove not-used IDA field from IPsec struct (Mohammad Kabat) [2112940]
- net/mlx5: Delete metadata handling logic (Mohammad Kabat) [2112940]
- net/mlx5_fpga: Drop INNOVA IPsec support (Mohammad Kabat) [2112940]
- net/mlx5: Cleanup kTLS function names and their exposure (Mohammad Kabat) [2112940]
- net/mlx5: Remove tls vs. ktls separation as it is the same (Mohammad Kabat) [2112940]
- net/mlx5: Remove indirection in TLS build (Mohammad Kabat) [2112940]
- net/mlx5: Reliably return TLS device capabilities (Mohammad Kabat) [2112940]
- net/mlx5_fpga: Drop INNOVA TLS support (Mohammad Kabat) [2112940]
Resolves: rhbz#2112940

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>